package com.dataeater.app.data

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Reads a REAL locked manifest, produced by the Python builder.
 *
 * WHY A FIXTURE TEST
 * ------------------
 * The other crypto tests use values generated by `make_crypto_vectors.py`,
 * which proves the maths agrees between the two languages. It does *not*
 * prove the app understands the files the builder actually writes.
 *
 * This test closes that gap. The manifest below was copied verbatim out of a
 * real locked `.dataeater` file, produced by:
 *
 *     tools/.venv/bin/python tools/tests/test_android_locked_fixture.py
 *
 * That script also asserts the locked file contains no readable text, so a
 * leak would be caught on the Python side at the same time.
 *
 * NOTE ON THE TWO RANDOM FIELDS
 * -----------------------------
 * `payload_nonce` and the `sha256` below change on every single build, because
 * a fresh nonce and a fresh encryption are the whole point. They are pinned
 * here at whatever one build happened to produce. They do not affect how the
 * app classifies the file, and no test should ever compare them.
 */
class LockedDatabaseFixtureTest {

    private val realLockedManifest = """
        {
          "format": "dataeater",
          "format_version": 1,
          "database_id": "demo",
          "name": "Demo Technical Knowledge Base",
          "description": "Small synthetic knowledge base about a fictional diesel fuel injection system. Used to test DataEater. Not real service data.",
          "language": "en",
          "created_utc": "2026-10-04T18:53:19Z",
          "builder_version": "0.1.0",
          "license": "CC0-1.0",
          "encryption": "aes-256-gcm",
          "counts": {
            "documents": 2,
            "chunks": 21
          },
          "files": {
            "payload.enc": {
              "sha256": "sha256:b1b7478d73153f116c2b4586de5daccf304b6b18017a628f2034fa5258c5d060",
              "bytes": 7504
            }
          },
          "payload_nonce": "bBS/eSPg645lMzEk",
          "creator": "Test Creator Ltd",
          "contact": "licences@test-creator.example",
          "creator_public_key": "MCowBQYDK2VwAyEABT10elTfT5weCVJPjP4gFWXuD+qO6mnMUJkTrWrCk8A="
        }
    """.trimIndent()

    @Test
    fun theAppsOwnBuilderOutputIsRecognisedAsLocked() {
        val status = DatabaseLock.statusOf(realLockedManifest)

        assertTrue(
            "the app must recognise a real locked file as locked, got $status",
            status is DatabaseLock.Status.Locked,
        )
        val locked = status as DatabaseLock.Status.Locked
        assertEquals("aes-256-gcm", locked.scheme)
    }

    /** The creator's details are the whole point of showing a locked file. */
    @Test
    fun theRealLockedFileShowsWhoToAsk() {
        val locked =
            DatabaseLock.statusOf(realLockedManifest) as DatabaseLock.Status.Locked

        assertTrue(locked.hasCreator)
        assertTrue(locked.hasContact)
        assertEquals("Test Creator Ltd", locked.manifest.creator)
        assertEquals("licences@test-creator.example", locked.manifest.contact)
    }

    /** Counts survive encryption, so the screen can say how big it is. */
    @Test
    fun theRealLockedFileStillReportsItsSize() {
        val locked =
            DatabaseLock.statusOf(realLockedManifest) as DatabaseLock.Status.Locked

        assertEquals("Demo Technical Knowledge Base", locked.manifest.name)
        assertEquals(2, locked.manifest.documentCount)
        assertEquals(21, locked.manifest.chunkCount)
    }

    /**
     * The plain demo and its locked version differ in exactly one way that
     * matters. If this ever fails, the app has lost the ability to tell them
     * apart and a customer would be shown a broken-file message for a
     * perfectly good database.
     */
    @Test
    fun thePlainDemoAndItsLockedVersionAreToldApart() {
        val plain = DatabaseLock.inspect(java.io.File("../dataeater/databases/demo.dataeater"))
        val locked = DatabaseLock.statusOf(realLockedManifest)

        assertTrue("bundled demo should be open", plain is DatabaseLock.Status.Open)
        assertTrue("encrypted copy should be locked", locked is DatabaseLock.Status.Locked)

        // Same database, same counts, same id. Only the encryption differs.
        assertEquals(
            (plain as DatabaseLock.Status.Open).manifest.databaseId,
            (locked as DatabaseLock.Status.Locked).manifest.databaseId,
        )
        assertEquals(
            plain.manifest.chunkCount,
            (locked as DatabaseLock.Status.Locked).manifest.chunkCount,
        )
    }
}