package com.dataeater.app.chat

import android.content.Context
import java.io.File

/**
 * Keeps conversations on the phone, so closing the app does not lose them.
 *
 * WHAT IS STORED
 * --------------
 * One JSON file per session, in the app's private folder. They are not on the
 * SD card and not in a shared location, because a conversation can contain
 * material from a database the user paid for.
 *
 * WHAT IS NOT STORED
 * ------------------
 * No model file, no database file, no Unlock Code. A session remembers only
 * the *name* of a model and the *name* of a database, and both are looked up
 * again in their own folders. If a file is gone, the session says so rather
 * than pretending.
 *
 * WHY PLAIN FILES AND NOT A DATABASE
 * ----------------------------------
 * The whole conversation is a few kilobytes. Reading one file at open and
 * writing it on change is simpler than a database, needs no dependency, and
 * cannot corrupt unrelated sessions.
 *
 * A note on the id: it is generated by the caller, and used as a file name, so
 * it is restricted to safe characters here rather than trusted.
 */
class SessionStore internal constructor(
    private val folder: File,
    private val publish: (File, File) -> Unit = { temporary, target ->
        java.nio.file.Files.move(
            temporary.toPath(), target.toPath(),
            java.nio.file.StandardCopyOption.ATOMIC_MOVE,
            java.nio.file.StandardCopyOption.REPLACE_EXISTING,
        )
    },
) : SessionRepository {

    constructor(context: Context) : this(File(context.filesDir, "sessions"))

    init { folder.mkdirs() }

    @Synchronized
    override fun all(): List<Session> =
        folder.listFiles()
            ?.filter { it.isFile && it.name.endsWith(".json") }
            ?.mapNotNull { file ->
                try {
                    SessionCodec.decodeSession(file.readText())
                } catch (problem: Exception) {
                    null
                }
            }
            ?: emptyList()

    @Synchronized
    override fun find(id: String): Session? {
        val file = fileFor(id) ?: return null
        return try {
            SessionCodec.decodeSession(file.readText())
        } catch (problem: Exception) {
            null
        }
    }

    /**
     * Writes a session.
     *
     * Flush a staged file, then atomically replace the old file in the same
     * private folder. A failed replacement retains the last successful save.
     *
     * @return true if it reached the disk
     */
    @Synchronized
    override fun save(session: Session): Boolean {
        val target = fileFor(session.id) ?: return false
        var temporary: File? = null
        return try {
            folder.mkdirs()
            temporary = File.createTempFile(".${session.id}-", ".tmp", folder)
            java.io.FileOutputStream(temporary).use { output ->
                output.write(SessionCodec.encodeSession(session).toByteArray(Charsets.UTF_8))
                output.fd.sync()
            }
            publish(temporary, target)
            true
        } catch (problem: Exception) {
            false
        } finally {
            temporary?.delete()
        }
    }

    @Synchronized
    override fun delete(id: String): Boolean = try {
        fileFor(id)?.delete() ?: false
    } catch (problem: Exception) {
        false
    }

    /**
     * Builds the next default name: "Session 1", then "Session 2", and so on.
     *
     * The number comes from the highest already in use plus one, so deleting
     * Session 2 and making a new one does not reuse the name of a conversation
     * the user still has elsewhere. Reusing a name would be genuinely
     * confusing when restoring a saved session.
     */
    override fun nextTitle(existing: List<Session>): String {
        val highest = existing.mapNotNull { it.title.numberAfter("Session") }
            .maxOrNull() ?: 0
        return "Session ${highest + 1}"
    }

    /** A fresh id. Time-based so it sorts, plus random so two cannot collide. */
    override fun newId(): String =
        "${System.currentTimeMillis()}-${java.util.UUID.randomUUID().toString().take(8)}"

    /**
     * The file for an id, or null if the id contains anything that should not
     * appear in a file name.
     *
     * Session ids are generated by this class, so this should never fire. It
     * exists because a file name built from outside data is how apps end up
     * writing outside the folder they meant to.
     */
    private fun fileFor(id: String): File? {
        val safe = id.trim()
        if (safe.isEmpty()) return null
        if (!safe.matches(Regex("[A-Za-z0-9._-]+"))) return null
        if (safe.contains("..")) return null
        return File(folder, "$safe.json")
    }

    /** "Session 12" -> 12. Anything else -> null. */
    private fun String.numberAfter(prefix: String): Int? =
        if (startsWith(prefix)) removePrefix(prefix).trim().toIntOrNull() else null
}
